# docker-compose.yml
version: '2.1' # version of docker-compose to use

networks:
    front:
      driver: bridge
    back:
      driver: bridge
services: # configuring each container
    mariadb:
        image: mariadb:10.5.8-focal
        #restart: always
        restart: "no"
        ports:
            - 3306:3306
        volumes:
            - ./data:/var/lib/mysql
            - ./initdb:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=rootpass
            - MYSQL_DATABASE=dbname
            - MYSQL_USER=dbuser
            - MYSQL_PASSWORD=dbpass
        networks:
            - back
    wp: # name of our wordpress container
        depends_on:
            - mariadb
        image: wordpress:5.6.0-fpm-alpine
        #build: ./wp/
        restart: "no"
        environment:
            - WORDPRESS_DB_HOST=mariadb:3306
            - WORDPRESS_DB_NAME=dbname
            - WORDPRESS_DB_USER=dbuser
            - WORDPRESS_DB_PASSWORD=dbpass
            - WORDPRESS_TABLE_PREFIX=prefix_
            - WORDPRESS_DEBUG=1
        volumes:
            - ./src/wordpress:/var/www/html
            - ./src/themes:/var/www/html/wp-content/themes
            - ./src/plugins:/var/www/html/wp-content/plugins
            - ./src/uploads:/var/www/html/wp-content/uploads
        networks:
            - front
            - back
    nginx:
        depends_on:
            - wp
        image: nginx:1.19.6-alpine
        restart: "no"
        ports:
            - 8000:80
        volumes:
            - ./nginx:/etc/nginx/conf.d
        volumes_from:
            - wp
        networks:
            - front
    wpcli:
        depends_on:
            - mariadb
            - wp
        image: wordpress:cli-2.4.0
        volumes_from:
            - wp
        networks:
            - front
            - back
        entrypoint: wp
        command: "--info"
